# Generated by Django 5.2 on 2025-04-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=200)),
                ('film_description', models.CharField(max_length=500)),
                ('film_rating', models.IntegerField()),
            ],
        ),
    ]
